/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandRouteImport } from './routes/brand'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as HelpRouteImport } from './routes/help'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SearchHistoryRouteImport } from './routes/search-history'
import { Route as SellerGuideRouteImport } from './routes/seller-guide'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StoreRouteImport } from './routes/store'
import { Route as WomenRouteImport } from './routes/women'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandRoute = BrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchHistoryRoute = SearchHistoryRouteImport.update({
  id: '/search-history',
  path: '/search-history',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerGuideRoute = SellerGuideRouteImport.update({
  id: '/seller-guide',
  path: '/seller-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const WomenRoute = WomenRouteImport.update({
  id: '/women',
  path: '/women',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/search-history': typeof SearchHistoryRoute
  '/seller-guide': typeof SellerGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/women': typeof WomenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/search-history': typeof SearchHistoryRoute
  '/seller-guide': typeof SellerGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/women': typeof WomenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/brand': typeof BrandRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/order-success': typeof OrderSuccessRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/search-history': typeof SearchHistoryRoute
  '/seller-guide': typeof SellerGuideRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/store': typeof StoreRoute
  '/women': typeof WomenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/brand'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/deals'
    | '/help'
    | '/notifications'
    | '/order-success'
    | '/products'
    | '/profile'
    | '/search-history'
    | '/seller-guide'
    | '/sitemap.xml'
    | '/store'
    | '/women'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/brand'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/deals'
    | '/help'
    | '/notifications'
    | '/order-success'
    | '/products'
    | '/profile'
    | '/search-history'
    | '/seller-guide'
    | '/sitemap.xml'
    | '/store'
    | '/women'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/brand'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/contact'
    | '/deals'
    | '/help'
    | '/notifications'
    | '/order-success'
    | '/products'
    | '/profile'
    | '/search-history'
    | '/seller-guide'
    | '/sitemap.xml'
    | '/store'
    | '/women'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  BrandRoute: typeof BrandRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  DealsRoute: typeof DealsRoute
  HelpRoute: typeof HelpRoute
  NotificationsRoute: typeof NotificationsRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  SearchHistoryRoute: typeof SearchHistoryRoute
  SellerGuideRoute: typeof SellerGuideRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StoreRoute: typeof StoreRoute
  WomenRoute: typeof WomenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand': {
      id: '/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof BrandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-history': {
      id: '/search-history'
      path: '/search-history'
      fullPath: '/search-history'
      preLoaderRoute: typeof SearchHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller-guide': {
      id: '/seller-guide'
      path: '/seller-guide'
      fullPath: '/seller-guide'
      preLoaderRoute: typeof SellerGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/women': {
      id: '/women'
      path: '/women'
      fullPath: '/women'
      preLoaderRoute: typeof WomenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  BrandRoute: BrandRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  DealsRoute: DealsRoute,
  HelpRoute: HelpRoute,
  NotificationsRoute: NotificationsRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  SearchHistoryRoute: SearchHistoryRoute,
  SellerGuideRoute: SellerGuideRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StoreRoute: StoreRoute,
  WomenRoute: WomenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
