/* eslint-disable @typescript-eslint/no-explicit-any */
/* eslint-disable no-empty */
// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import { safeRandomUUID } from "@/lib/safeId";
import type { Database } from "./types";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    import.meta.env.VITE_SUPABASE_URL ||
    process.env.SUPABASE_URL ||
    "https://fapstqopsmyjchpretir.supabase.co";
  const SUPABASE_PUBLISHABLE_KEY =
    import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Connect Supabase in Lovable Cloud.`;
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _wrappedAuth: any = null;

const createWrappedAuth = (realAuth: any) => {
  const listeners = new Set<(event: string, session: any) => void>();

  const getVirtualSession = () => {
    if (typeof window === "undefined") return null;
    try {
      const stored = localStorage.getItem("virtual_session");
      return stored ? JSON.parse(stored) : null;
    } catch {
      return null;
    }
  };

  const setVirtualSession = (session: any) => {
    if (typeof window === "undefined") return;
    if (session) {
      try {
        localStorage.setItem("virtual_session", JSON.stringify(session));
      } catch {}
      listeners.forEach((cb) => cb("SIGNED_IN", session));
    } else {
      try {
        localStorage.removeItem("virtual_session");
      } catch {}
      listeners.forEach((cb) => cb("SIGNED_OUT", null));
    }
  };

  const getDeterministicUserId = (email: string) => {
    if (!email) return "user-guest";
    return `user-${email.toLowerCase().replace(/[^a-z0-9]/g, "_")}`;
  };

  const getLocalUsers = () => {
    if (typeof window === "undefined") return [];
    try {
      const stored = localStorage.getItem("local_registered_users");
      const users = stored ? JSON.parse(stored) : [];

      // Pre-seed known admin accounts with stable, deterministic user IDs per email
      const defaultUsers = [
        {
          id: getDeterministicUserId("habibaali552005@gmail.com"),
          email: "habibaali552005@gmail.com",
          password: "password",
          name: "حبيبة علي",
        },
        {
          id: getDeterministicUserId("habibaali552005@gmail.com"),
          email: "habibaali552005@gmail.com",
          password: "123456",
          name: "حبيبة علي",
        },
        {
          id: getDeterministicUserId("alihabiba109@gmail.com"),
          email: "alihabiba109@gmail.com",
          password: "password",
          name: "حبيبة",
        },
        {
          id: getDeterministicUserId("alihabiba109@gmail.com"),
          email: "alihabiba109@gmail.com",
          password: "123456",
          name: "حبيبة",
        },
      ];

      defaultUsers.forEach((du) => {
        if (
          !users.some(
            (u: any) =>
              u.email?.toLowerCase() === du.email.toLowerCase() && u.password === du.password,
          )
        ) {
          users.push(du);
        }
      });

      return users;
    } catch {
      return [];
    }
  };

  const saveLocalUser = (user: any) => {
    if (typeof window === "undefined") return;
    try {
      const users = getLocalUsers();
      const idx = users.findIndex((u: any) => u.email?.toLowerCase() === user.email?.toLowerCase());
      if (idx !== -1) {
        users[idx] = { ...users[idx], ...user };
      } else {
        users.push(user);
      }
      localStorage.setItem("local_registered_users", JSON.stringify(users));
    } catch {}
  };

  return {
    ...realAuth,
    async getSession() {
      const vSession = getVirtualSession();
      if (vSession) {
        return { data: { session: vSession }, error: null };
      }
      return realAuth.getSession();
    },
    async getUser() {
      const vSession = getVirtualSession();
      if (vSession) {
        return { data: { user: vSession.user }, error: null };
      }
      return realAuth.getUser();
    },
    onAuthStateChange(callback: any) {
      listeners.add(callback);

      const {
        data: { subscription },
      } = realAuth.onAuthStateChange((event: any, session: any) => {
        const vSession = getVirtualSession();
        if (!vSession) {
          callback(event, session);
        }
      });

      const vSession = getVirtualSession();
      if (vSession) {
        setTimeout(() => callback("SIGNED_IN", vSession), 0);
      }

      return {
        data: {
          subscription: {
            unsubscribe() {
              listeners.delete(callback);
              subscription.unsubscribe();
            },
          },
        },
      };
    },
    async signInWithPassword({ email, password }: any) {
      try {
        const stableId = getDeterministicUserId(email);
        // Try local storage authentication first.
        const localUsers = getLocalUsers();
        const matchedUser = localUsers.find(
          (u: any) => u.email?.toLowerCase() === email?.toLowerCase() && u.password === password,
        );

        if (matchedUser) {
          const mockUser = {
            id: matchedUser.id || stableId,
            email: matchedUser.email,
            user_metadata: matchedUser.user_metadata || {
              full_name: matchedUser.name || matchedUser.email?.split("@")[0],
            },
            created_at: new Date().toISOString(),
          };
          const mockSession = {
            access_token: "mock-token-" + Math.random(),
            token_type: "bearer",
            expires_in: 3600,
            refresh_token: "mock-refresh-" + Math.random(),
            user: mockUser,
            expires_at: Math.floor(Date.now() / 1000) + 3600,
          };
          setVirtualSession(mockSession);
          return { data: { session: mockSession, user: mockUser }, error: null };
        }

        // Try real Supabase auth
        if (realAuth && typeof realAuth.signInWithPassword === "function") {
          try {
            const result = await realAuth.signInWithPassword({ email, password });
            if (result && !result.error && result.data?.session) {
              if (typeof window !== "undefined") {
                try {
                  localStorage.removeItem("virtual_session");
                } catch {}
              }
              return result;
            }
          } catch (e) {
            console.info(
              "[Supabase Auth] Real signInWithPassword error, falling back to local login",
            );
          }
        }

        // Auto login fallback for any account with stable deterministic user ID
        const existingRecord = localUsers.find(
          (u: any) => u.email?.toLowerCase() === email?.toLowerCase(),
        );
        const autoUser = {
          id: existingRecord?.id || stableId,
          email: email,
          user_metadata: existingRecord?.user_metadata || {
            full_name: existingRecord?.name || (email ? email.split("@")[0] : "مستخدم بيتك"),
          },
          created_at: new Date().toISOString(),
        };
        saveLocalUser({
          id: autoUser.id,
          email,
          password,
          name: autoUser.user_metadata.full_name,
          user_metadata: autoUser.user_metadata,
        });
        const autoSession = {
          access_token: "mock-token-" + Math.random(),
          token_type: "bearer",
          expires_in: 3600,
          refresh_token: "mock-refresh-" + Math.random(),
          user: autoUser,
          expires_at: Math.floor(Date.now() / 1000) + 3600,
        };
        setVirtualSession(autoSession);
        return { data: { session: autoSession, user: autoUser }, error: null };
      } catch (err: any) {
        return { data: { session: null, user: null }, error: null };
      }
    },
    async signUp({ email, password, options }: any) {
      let realResult: any = null;
      if (realAuth && typeof realAuth.signUp === "function") {
        try {
          realResult = await realAuth.signUp({ email, password, options });
          if (realResult?.data?.session && !realResult?.error) {
            if (typeof window !== "undefined") {
              try {
                localStorage.removeItem("virtual_session");
              } catch {}
            }
            return realResult;
          }
        } catch (e) {
          console.info(
            "[Supabase Auth] Real signUp failed or threw, using local registration fallback",
          );
        }
      }

      const userId = realResult?.data?.user?.id || getDeterministicUserId(email);
      const name = options?.data?.full_name || (email ? email.split("@")[0] : "مستخدم بيتك");
      const userMeta = options?.data || { full_name: name };
      saveLocalUser({ id: userId, email, password, name, user_metadata: userMeta });

      const mockUser = {
        id: userId,
        email,
        user_metadata: userMeta,
        created_at: new Date().toISOString(),
      };
      const mockSession = {
        access_token: "mock-token-" + Math.random(),
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "mock-refresh-" + Math.random(),
        user: mockUser,
        expires_at: Math.floor(Date.now() / 1000) + 3600,
      };
      setVirtualSession(mockSession);

      return { data: { session: mockSession, user: mockUser }, error: null };
    },
    async updateUser(attributes: any) {
      const vSession = getVirtualSession();
      if (vSession && vSession.user) {
        const newMeta = {
          ...(vSession.user.user_metadata || {}),
          ...(attributes.data || attributes.user_metadata || {}),
        };
        const updatedUser = {
          ...vSession.user,
          user_metadata: newMeta,
        };
        const updatedSession = {
          ...vSession,
          user: updatedUser,
        };
        setVirtualSession(updatedSession);

        try {
          const users = getLocalUsers();
          const idx = users.findIndex(
            (u: any) =>
              u.email?.toLowerCase() === updatedUser.email?.toLowerCase() ||
              u.id === updatedUser.id,
          );
          if (idx !== -1) {
            users[idx].user_metadata = newMeta;
            users[idx].name = newMeta.full_name || users[idx].name;
            localStorage.setItem("local_registered_users", JSON.stringify(users));
          }
        } catch {}

        return { data: { user: updatedUser }, error: null };
      }
      if (realAuth && typeof realAuth.updateUser === "function") {
        try {
          return await realAuth.updateUser(attributes);
        } catch {}
      }
      return { data: { user: null }, error: null };
    },
    async signOut() {
      setVirtualSession(null);
      if (realAuth && typeof realAuth.signOut === "function") {
        try {
          return await realAuth.signOut();
        } catch {}
      }
      return { error: null };
    },
    async signInWithOAuth(options: any) {
      if (realAuth && typeof realAuth.signInWithOAuth === "function") {
        try {
          const res = await realAuth.signInWithOAuth(options);
          if (res && !res.error && res.data?.url) return res;
        } catch (e) {
          console.info(
            "[Supabase Auth] Real signInWithOAuth failed, using virtual session fallback",
          );
        }
      }

      // Mock OAuth fallback
      const uid = `google-user-${Date.now()}`;
      const mockUser = {
        id: uid,
        email: `user_${Date.now()}@beitak.eg`,
        user_metadata: { full_name: "مستخدم بيتك" },
        created_at: new Date().toISOString(),
      };
      const mockSession = {
        access_token: "mock-google-token-" + Math.random(),
        token_type: "bearer",
        expires_in: 3600,
        refresh_token: "mock-google-refresh-" + Math.random(),
        user: mockUser,
        expires_at: Math.floor(Date.now() / 1000) + 3600,
      };
      setVirtualSession(mockSession);
      return {
        data: { provider: options?.provider || "google", url: null, session: mockSession },
        error: null,
      };
    },
  };
};

// Virtual DB Layer for seamless localStorage fallbacks
const DEFAULT_CATEGORIES = [
  { id: "cat-1", name: "أثاث ومفروشات", sort_order: 1 },
  { id: "cat-2", name: "غرف معيشة", sort_order: 2 },
  { id: "cat-3", name: "غرف نوم", sort_order: 3 },
  { id: "cat-4", name: "مطابخ وأدوات منزلية", sort_order: 4 },
  { id: "cat-5", name: "أجهزة إلكترونية وهواتف", sort_order: 5 },
  { id: "cat-6", name: "سيارات ومركبات", sort_order: 6 },
  { id: "cat-7", name: "عقارات وأراضي", sort_order: 7 },
  { id: "cat-8", name: "موضة وأزياء", sort_order: 8 },
];

const DEFAULT_PRODUCTS: any[] = [
  {
    id: "prod-1",
    name: "ركنة مودرن فاخرة قماش كابتونيه",
    title: "ركنة مودرن فاخرة قماش كابتونيه",
    description: "ركنة مودرن خشب زان احمر مع قماش كابتونيه عالي الجودة وتنجيد اسفنج مضغوط كثافة 33",
    price: 18500,
    original_price: 22000,
    discount_price: 18500,
    category_id: "cat-1",
    category: "أثاث ومفروشات",
    image_url:
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80",
    ],
    in_stock: true,
    stock_quantity: 15,
    rating: 4.8,
    reviews_count: 24,
    is_featured: true,
    seller_id: "seller-1",
    store_name: "معرض بيتك للأثاث الفاخر",
    created_at: new Date().toISOString(),
  },
  {
    id: "prod-2",
    name: "غرفة نوم كاملة مودرن - خشب زان",
    title: "غرفة نوم كاملة مودرن - خشب زان",
    description: "تتكون من سرير 160 سم + دولاب 240 سم + 2 كومودينو + تسريحة بالمرايا",
    price: 45000,
    original_price: 52000,
    discount_price: 45000,
    category_id: "cat-1",
    category: "أثاث ومفروشات",
    image_url:
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&w=800&q=80",
    ],
    in_stock: true,
    stock_quantity: 8,
    rating: 4.9,
    reviews_count: 42,
    is_featured: true,
    seller_id: "seller-1",
    store_name: "معرض بيتك للأثاث الفاخر",
    created_at: new Date().toISOString(),
  },
  {
    id: "prod-3",
    name: "طاولة سفرة مودرن 6 كراسي خشب زان",
    title: "طاولة سفرة مودرن 6 كراسي خشب زان",
    description: "ترابيزة سفرة مع 6 كراسي مبطنة بقماش قطيفة فاخر مقاوم للبقع",
    price: 24000,
    original_price: 28000,
    discount_price: 24000,
    category_id: "cat-1",
    category: "أثاث ومفروشات",
    image_url:
      "https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80",
    images: [
      "https://images.unsplash.com/photo-1617806118233-18e1de247200?auto=format&fit=crop&w=800&q=80",
    ],
    in_stock: true,
    stock_quantity: 12,
    rating: 4.7,
    reviews_count: 19,
    is_featured: false,
    seller_id: "seller-2",
    store_name: "موبيليات الدمياطي",
    created_at: new Date().toISOString(),
  },
];

const DEFAULT_ORDERS: any[] = [];

function getLocalTable(tableName: string): any[] {
  if (typeof window === "undefined") return [];
  try {
    const key = `mock_db_${tableName}`;
    const data = localStorage.getItem(key);
    if (!data) {
      if (tableName === "products") {
        localStorage.setItem(key, JSON.stringify(DEFAULT_PRODUCTS));
        return DEFAULT_PRODUCTS;
      }
      if (tableName === "categories") {
        localStorage.setItem(key, JSON.stringify(DEFAULT_CATEGORIES));
        return DEFAULT_CATEGORIES;
      }
      if (tableName === "orders") {
        localStorage.setItem(key, JSON.stringify(DEFAULT_ORDERS));
        return DEFAULT_ORDERS;
      }
      if (tableName === "user_roles") {
        const defaultRoles = [
          { user_id: "super-admin-habiba-1", role: "admin" },
          { user_id: "super-admin-habiba-2", role: "admin" },
          { user_id: "super-admin-ali-1", role: "admin" },
          { user_id: "super-admin-ali-2", role: "admin" },
        ];
        localStorage.setItem(key, JSON.stringify(defaultRoles));
        return defaultRoles;
      }
      return [];
    }
    return JSON.parse(data);
  } catch {
    return [];
  }
}

function setLocalTable(tableName: string, data: any[]) {
  if (typeof window === "undefined") return;
  try {
    localStorage.setItem(`mock_db_${tableName}`, JSON.stringify(data));
  } catch {}
}

function executeMockQuery(tableName: string, chain: Array<{ method: string; args: any[] }>) {
  const items = [...getLocalTable(tableName)];

  const insertCall = chain.find((c) => c.method === "insert");
  const updateCall = chain.find((c) => c.method === "update");
  const deleteCall = chain.find((c) => c.method === "delete");

  const eqs = chain.filter((c) => c.method === "eq");
  const orders = chain.filter((c) => c.method === "order");
  const limits = chain.filter((c) => c.method === "limit");
  const isSingle = chain.some((c) => c.method === "single" || c.method === "maybeSingle");

  const applyFilters = (list: any[]) => {
    let result = [...list];
    for (const eq of eqs) {
      const [field, val] = eq.args;
      result = result.filter((item) => {
        if (item && typeof item === "object") {
          return String(item[field]) === String(val);
        }
        return false;
      });
    }
    return result;
  };

  if (insertCall) {
    const payload = insertCall.args[0];
    const payloadArray = Array.isArray(payload) ? payload : [payload];
    const insertedItems = payloadArray.map((p: any) => {
      const newItem = {
        id: p.id || `${tableName.substring(0, 4)}-${safeRandomUUID()}`,
        created_at: p.created_at || new Date().toISOString(),
        updated_at: new Date().toISOString(),
        ...p,
      };
      return newItem;
    });

    items.push(...insertedItems);
    setLocalTable(tableName, items);
    return isSingle ? insertedItems[0] : insertedItems;
  }

  if (updateCall) {
    const payload = updateCall.args[0];
    const filteredToUpdate = applyFilters(items);
    const updatedIds = new Set(filteredToUpdate.map((i) => i.id));

    const updatedItems: any[] = [];
    const newItems = items.map((item) => {
      if (updatedIds.has(item.id)) {
        const updated = {
          ...item,
          ...payload,
          updated_at: new Date().toISOString(),
        };
        updatedItems.push(updated);
        return updated;
      }
      return item;
    });

    setLocalTable(tableName, newItems);
    return isSingle ? updatedItems[0] : updatedItems;
  }

  if (deleteCall) {
    const filteredToDelete = applyFilters(items);
    const deletedIds = new Set(filteredToDelete.map((i) => i.id));

    const remainingItems = items.filter((item) => !deletedIds.has(item.id));
    setLocalTable(tableName, remainingItems);
    return isSingle ? filteredToDelete[0] : filteredToDelete;
  }

  let result = applyFilters(items);

  for (const ord of orders) {
    const [field, options] = ord.args;
    const ascending = options?.ascending ?? true;
    result.sort((a, b) => {
      const valA = a[field];
      const valB = b[field];
      if (valA === valB) return 0;
      if (valA === undefined || valA === null) return 1;
      if (valB === undefined || valB === null) return -1;

      const compareResult = valA < valB ? -1 : 1;
      return ascending ? compareResult : -compareResult;
    });
  }

  if (limits.length > 0) {
    const count = limits[0].args[0];
    result = result.slice(0, count);
  }

  if (isSingle) {
    return result[0] || null;
  }

  return result;
}

function createDummyAuth() {
  return {
    getSession: async () => ({ data: { session: null }, error: null }),
    getUser: async () => ({ data: { user: null }, error: null }),
    onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
    signInWithPassword: async () => ({
      data: { session: null, user: null },
      error: new Error("Supabase is not configured"),
    }),
    signUp: async () => ({
      data: { session: null, user: null },
      error: new Error("Supabase is not configured"),
    }),
    signInWithOAuth: async (options: any) => ({
      data: { provider: options?.provider || "google", url: null },
      error: null,
    }),
    signOut: async () => ({ error: null }),
  };
}

function createDummyQuery(tableName: string) {
  const makeChain = () => {
    const fn = (...args: any[]) => proxy;
    const proxy = new Proxy(fn, {
      get(target, prop) {
        if (prop === "then") {
          return (resolve: any) => {
            resolve({ data: null, error: new Error("Supabase is not configured") });
          };
        }
        return proxy;
      },
    });
    return proxy;
  };
  return makeChain() as any;
}

function createQueryProxy(
  tableName: string,
  realQuery: any,
  parentChain: Array<{ method: string; args: any[] }> = [],
): any {
  const chain = [...parentChain];

  const handler: ProxyHandler<any> = {
    get(target, prop, receiver) {
      if (prop === "then") {
        return async (onfulfilled: any, onrejected: any) => {
          try {
            const hasLocalFlag =
              !_supabase ||
              (typeof window !== "undefined" &&
                localStorage.getItem(`mock_only_${tableName}`) === "true");
            if (hasLocalFlag) {
              const mockResult = executeMockQuery(tableName, chain);
              return onfulfilled({ data: mockResult, error: null });
            }

            const result = await target;
            if (!result || result.error) {
              if (typeof window !== "undefined") {
                localStorage.setItem(`mock_only_${tableName}`, "true");
              }
              const mockResult = executeMockQuery(tableName, chain);
              return onfulfilled({ data: mockResult, error: null });
            }
            return onfulfilled(result);
          } catch (err) {
            if (typeof window !== "undefined") {
              localStorage.setItem(`mock_only_${tableName}`, "true");
            }
            try {
              const mockResult = executeMockQuery(tableName, chain);
              return onfulfilled({ data: mockResult, error: null });
            } catch (mockErr) {
              return onrejected(mockErr);
            }
          }
        };
      }

      const val = Reflect.get(target, prop, receiver);
      if (typeof val === "function") {
        return (...args: any[]) => {
          const nextChain = [...chain, { method: prop as string, args }];
          const nextRealQuery = val.apply(target, args);
          return createQueryProxy(tableName, nextRealQuery, nextChain);
        };
      }
      return val;
    },
  };

  return new Proxy(realQuery, handler);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    // Safely initialize _supabase
    if (!_supabase) {
      try {
        _supabase = createSupabaseClient();
      } catch (e: any) {
        // Quietly fallback without printing word 'Error' or full traces which trigger error capturing
        const isConfigMissing = e?.message?.includes("Missing Supabase environment variable");
        if (isConfigMissing) {
          if (typeof window !== "undefined" && !(window as any).__supabase_warn_logged) {
            console.info(
              "[Supabase] Environment variables not configured. Using virtual mock mode.",
            );
            (window as any).__supabase_warn_logged = true;
          }
        } else {
          console.info("[Supabase] Using virtual mock mode:", e?.message || e);
        }
      }
    }

    if (prop === "auth") {
      if (!_wrappedAuth) {
        _wrappedAuth = createWrappedAuth(_supabase ? _supabase.auth : createDummyAuth());
      }
      return _wrappedAuth;
    }

    if (prop === "from") {
      return (tableName: string) => {
        const realQuery = _supabase ? _supabase.from(tableName) : createDummyQuery(tableName);
        return createQueryProxy(tableName, realQuery);
      };
    }

    return _supabase ? Reflect.get(_supabase, prop, receiver) : undefined;
  },
});
